sudo: required

services:
  - docker

jobs:
  include:
    - stage: test build
      script:
      # pull container
      - docker pull cmbiwer/vizaly-cbench:v4
      # create a volume and run testing/travis/test_build.sh
      - docker run -v "$(pwd)":/src/VizAly-CBench -it cmbiwer/vizaly-cbench:v4 /bin/bash /src/VizAly-CBench/testing/travis/test_build.sh
